info:
  app:
    name: swapi-spring-web
    version: 0.0.4-SNAPSHOT

server:
  port: 8080
  error:
    whitelabel:
      enabled: true

#logging:
#  level:
#    web: DEBUG
#    swapi: TRACE


management:
  endpoints:
    web:
      exposure:
        include: '*'


estaGracefulShutdownWaitSeconds: 0
