apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: swapi-spring-webflux-hpa
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: swapi-spring-webflux
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50
