apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "swapi-spring-webflux"
    version: "0.0.4-SNAPSHOT"
    group: "swapi"
  name: "swapi-spring-webflux"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "swapi-spring-webflux"
      version: "0.0.4-SNAPSHOT"
      group: "swapi"
  template:
    metadata:
      labels:
        app: "swapi-spring-webflux"
        version: "0.0.4-SNAPSHOT"
        group: "swapi"
    spec:
      containers:
        - name: "swapi-spring-webflux"
          image: "docker.local/swapi/swapi-spring-webflux:0.0.4-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /var/log
              name: varlog
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: "/actuator/info"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              name: "http"
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
        - name: filebeat-sidecar
          image: "docker.elastic.co/beats/filebeat:7.4.1"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config
              mountPath: /usr/share/filebeat/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
      imagePullSecrets:
        - name: docker-local-registry-creds
      volumes:
        - name: varlog
          emptyDir: {}
        - name: config
          configMap:
            #defaultMode: 0600
            name: swapi-filebeat-config
