apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "swapi-spring-webflux"
    version: "0.0.4-SNAPSHOT"
    group: "swapi"
  name: "swapi-spring-webflux"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "swapi-spring-webflux"
      version: "0.0.4-SNAPSHOT"
      group: "swapi"
  template:
    metadata:
      labels:
        app: "swapi-spring-webflux"
        version: "0.0.4-SNAPSHOT"
        group: "swapi"
    spec:
      containers:
        - name: "swapi-spring-webflux"
          image: "docker.local/swapi/swapi-spring-webflux:0.0.4-SNAPSHOT"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "512Mi"
              cpu: "1.0"
          livenessProbe:
            httpGet:
              path: "/actuator/info"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 3
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              name: "http"
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 10
      imagePullSecrets:
        - name: docker-local-registry-creds
