apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: swapi-spring-webflux-hpa
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: swapi-spring-webflux
  targetCPUUtilizationPercentage: 20
