apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "swapi-spring-webflux"
    group: "swapi"
  name: "swapi-spring-webflux-lb"
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: "swapi-spring-webflux"
    group: "swapi"
  type: LoadBalancer
