apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: swapi-spring-web-hpa
  labels:
    group: "swapi"
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: swapi-spring-web
  targetCPUUtilizationPercentage: 20
