spring:

  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    #http://hsqldb.org/doc/2.0/guide/dbproperties-chapt.html
    url: "jdbc:hsqldb:mem:swapi"
    username: sa
    password:

  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: build/generated-sources/sql/hsqldb/schema.sql
    show-sql: true
    generate-ddl: true

